apiVersion: v1
kind: Service
metadata:
  name: "gateway-api-service"
  namespace: "infocenter-v2-be"
spec:
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 31234
      protocol: TCP
  type: NodePort
  selector:
    app: "gateway-api"