name: Deploy To Demo

on:
  push:
    tags:
      - demo
      - 'demo/*'

jobs:
  generate-tag:
    name: Generate Tag
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.tag_name.outputs.tag_name }}
    steps:
      - name: Generate Tag Name
        id: tag_name
        run: echo "::set-output name=tag_name::$(date --rfc-3339=date)_${GITHUB_SHA::7}"

  build-applications-service:
    name: Build Applications Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Applications App
        run: |
          docker build -t $REGISTRY/$REPOSITORY:applications-app --build-arg ENVIRONMENT="demo" --build-arg DB_HOST=$DB_HOST --build-arg DB_USER=$DB_USER --build-arg DB_PASS=$DB_PASS ./applications-app/
          docker push $REGISTRY/$REPOSITORY:applications-app
          aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --force-new-deployment
        env:
          DB_HOST: ${{ secrets.DEMO_DB_HOST}}
          DB_USER: ${{ secrets.DEMO_DB_USER}}
          DB_PASS: ${{ secrets.DEMO_DB_PASS}}
          ECS_CLUSTER: infocenter-v2-be--demo
          ECS_SERVICE: demo-applications-app
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: infocenter-v2-be-demo

      - uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: 'Backend Deployment to Demo Failed!',
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: ${{ failure() || cancelled() }}

  build-authentication-service:
    name: Build Authentication Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Authentication App
        run: |
          docker build -t $REGISTRY/$REPOSITORY:authentication --build-arg ENVIRONMENT="demo" ./authentication/
          docker push $REGISTRY/$REPOSITORY:authentication
          aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --force-new-deployment
        env:
          ECS_CLUSTER: infocenter-v2-be--demo
          ECS_SERVICE: demo-authentication
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: infocenter-v2-be-demo

      - uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: 'Backend Deployment to Demo Failed!',
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: ${{ failure() || cancelled() }}

  build-students-service:
    name: Build Students Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Students App
        run: |
          docker build -t $REGISTRY/$REPOSITORY:students-app --build-arg ENVIRONMENT="demo" --build-arg DB_HOST=$DB_HOST --build-arg DB_USER=$DB_USER --build-arg DB_PASS=$DB_PASS ./students-app/
          docker push $REGISTRY/$REPOSITORY:students-app
          aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --force-new-deployment
        env:
          DB_HOST: ${{ secrets.DEMO_DB_HOST}}
          DB_USER: ${{ secrets.DEMO_DB_USER}}
          DB_PASS: ${{ secrets.DEMO_DB_PASS}}
          ECS_CLUSTER: infocenter-v2-be--demo
          ECS_SERVICE: demo-students-app
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: infocenter-v2-be-demo

      - uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: 'Backend Deployment to Demo Failed!',
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: ${{ failure() || cancelled() }}

  build-users-service:
    name: Build Users Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Users App
        run: |
          docker build -t $REGISTRY/$REPOSITORY:users-app --build-arg ENVIRONMENT="demo" --build-arg DB_HOST=$DB_HOST --build-arg DB_USER=$DB_USER --build-arg DB_PASS=$DB_PASS ./users-app/
          docker push $REGISTRY/$REPOSITORY:users-app
          aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --force-new-deployment
        env:
          DB_HOST: ${{ secrets.DEMO_DB_HOST}}
          DB_USER: ${{ secrets.DEMO_DB_USER}}
          DB_PASS: ${{ secrets.DEMO_DB_PASS}}
          ECS_CLUSTER: infocenter-v2-be--demo
          ECS_SERVICE: demo-users-app
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: infocenter-v2-be-demo

      - uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: 'Backend Deployment to Demo Failed!',
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: ${{ failure() || cancelled() }}

  build-media-service:
    name: Build Media Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Media App
        run: |
          docker build -t $REGISTRY/$REPOSITORY:media-app --build-arg ENVIRONMENT="demo" ./media-app/
          docker push $REGISTRY/$REPOSITORY:media-app
          aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --force-new-deployment
        env:
          ECS_CLUSTER: infocenter-v2-be--demo
          ECS_SERVICE: demo-media-app
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: infocenter-v2-be-demo

      - uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: 'Backend Deployment to Demo Failed!',
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: ${{ failure() || cancelled() }}

  build-gateway-service:
    name: Build Gateway Service
    runs-on: ubuntu-latest
    needs: [build-applications-service, build-authentication-service, build-students-service, build-users-service]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Gateway App
        run: |
          docker build -t $REGISTRY/$REPOSITORY:gateway --build-arg ENVIRONMENT="demo" ./gateway/
          docker push $REGISTRY/$REPOSITORY:gateway
          aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --force-new-deployment
        env:
          ECS_CLUSTER: infocenter-v2-be--demo
          ECS_SERVICE: demo-gateway
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: infocenter-v2-be-demo

      - uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: 'Backend Deployment to Demo Failed!',
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: ${{ failure() || cancelled() }}

  send-slack-success-message:
    name: Send Slack Success Message
    runs-on: ubuntu-latest
    needs:
      [
        generate-tag,
        build-applications-service,
        build-authentication-service,
        build-students-service,
        build-users-service,
        build-gateway-service,
        build-media-service,
      ]
    steps:
      - uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: 'Backend Deployment to Demo Successful!',
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
